import { ChangeDetectionStrategy, Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { GetMissionExecution, ListAdminUsers, ListAircraft, ListIndividualAssignments, ListManeuvers, ListMissionTypes, ListPrograms, UpdateMissionExecution } from '@core/application';
import type { ManeuverBankEntity, ManeuverGrade, MissionExecutionEntity, MissionExecutionWriteInput, MissionResult, UserEntity } from '@core/domain/entities';
import { DomainError } from '@core/domain/errors/domain-error';
import { Alert } from '@shared/components/alert/alert';
import { Button } from '@shared/components/button/button';
import { Card } from '@shared/components/card/card';
import { UiAvatar } from '@shared/components/ui-avatar/ui-avatar';
import { UiFormCard } from '@shared/components/ui-form-card/ui-form-card';
import { UiInput } from '@shared/components/ui-input/ui-input';
import { UiLoading } from '@shared/components/ui-loading/ui-loading';
import { UiSelect } from '@shared/components/ui-select/ui-select';
import { UiTextarea } from '@shared/components/ui-textarea/ui-textarea';
import { UiSteps, type StepItem } from '@shared/components/ui-steps/ui-steps';
import type { ChoiceOption } from '@shared/models/choice.model';
import { firstValueFrom, forkJoin } from 'rxjs';
import { ToastService } from '@shared/components/ui-toast/toast.service';

interface EvaluationRow { maneuver: ManeuverBankEntity; grade: ManeuverGrade | null; observation: string; evidenceName: string | null; }

@Component({ selector: 'app-mission-workspace', changeDetection: ChangeDetectionStrategy.OnPush, imports: [ReactiveFormsModule, Alert, Button, Card, UiAvatar, UiFormCard, UiInput, UiLoading, UiSelect, UiSteps, UiTextarea], templateUrl: './mission-workspace.page.html', styleUrl: './mission-workspace.page.scss' })
export class MissionWorkspacePage {
  private readonly destroyRef = inject(DestroyRef); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly getExecution = inject(GetMissionExecution); private readonly updateExecution = inject(UpdateMissionExecution); private readonly listAssignments = inject(ListIndividualAssignments); private readonly listUsers = inject(ListAdminUsers); private readonly listPrograms = inject(ListPrograms); private readonly listMissions = inject(ListMissionTypes); private readonly listManeuvers = inject(ListManeuvers); private readonly listAircraft = inject(ListAircraft); private readonly toast = inject(ToastService);
  readonly loading = signal(true); readonly saving = signal(false); readonly error = signal<string | null>(null); readonly execution = signal<MissionExecutionEntity | null>(null); readonly rows = signal<EvaluationRow[]>([]); readonly openManeuver = signal<string | null>(null); readonly assignment = signal<any>(null); readonly users = signal<UserEntity[]>([]); readonly aircraft = signal<ChoiceOption[]>([]); readonly title = computed(() => this.assignment()?.missionId ?? 'Workspace de misión'); readonly grades: ChoiceOption[] = ['D', 'I', 'R', 'B', 'E', 'NC', 'P'].map((value) => ({ value, label: value })); readonly results: ChoiceOption[] = [{ value: 'approved', label: 'Aprobado' }, { value: 'approved-observations', label: 'Aprobado con observaciones' }, { value: 'reinforcement', label: 'Requiere refuerzo' }, { value: 'failed', label: 'Desaprobado' }]; readonly steps: StepItem[] = [{ label: 'Programada' }, { label: 'En ejecución' }, { label: 'Calificada' }, { label: 'Pendiente validación' }, { label: 'Aprobada' }]; readonly form = new FormGroup({ startDate: new FormControl('', { nonNullable: true }), startTime: new FormControl('', { nonNullable: true }), takeoffTime: new FormControl('', { nonNullable: true }), landingTime: new FormControl('', { nonNullable: true }), executedHours: new FormControl(0, { nonNullable: true, validators: [Validators.min(0.01)] }), aircraftId: new FormControl('', { nonNullable: true }), observations: new FormControl('', { nonNullable: true }), strengths: new FormControl('', { nonNullable: true }), improvements: new FormControl('', { nonNullable: true }), recommendations: new FormControl('', { nonNullable: true }), result: new FormControl<MissionResult | null>(null, { nonNullable: false }) });
  readonly evaluatedCount = computed(() => this.rows().filter((row) => row.grade).length); readonly average = computed(() => { const values: Record<string, number> = { D: 0, I: 25, R: 50, B: 75, E: 100, NC: 0, P: 100 }; const graded = this.rows().filter((row) => row.grade); return graded.length ? Math.round(graded.reduce((sum, row) => sum + values[row.grade as string], 0) / graded.length) : 0; }); readonly canClose = computed(() => this.evaluatedCount() === this.rows().length && this.rows().length > 0 && this.form.controls.executedHours.value > 0);
  constructor() { const id = this.route.snapshot.paramMap.get('id'); if (!id) return; forkJoin({ execution: this.getExecution.execute(id), assignments: this.listAssignments.execute(), users: this.listUsers.execute(), programs: this.listPrograms.execute(), missions: this.listMissions.execute(), maneuvers: this.listManeuvers.execute(), aircraft: this.listAircraft.execute() }).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: ({ execution, assignments, users, aircraft, maneuvers }) => { this.execution.set(execution); this.assignment.set(assignments.find((item) => item.id === execution.individualAssignmentId)); this.users.set(users); this.aircraft.set(aircraft.map((item) => ({ value: item.id, label: item.registration }))); this.form.patchValue({ startDate: execution.startDate ?? '', startTime: execution.startTime ?? '', takeoffTime: execution.takeoffTime, landingTime: execution.landingTime, executedHours: execution.executedHours, aircraftId: execution.aircraftId ?? '', observations: execution.observations, strengths: execution.strengths, improvements: execution.improvements, recommendations: execution.recommendations, result: execution.result }); this.rows.set(execution.evaluations.map((evaluation) => ({ maneuver: maneuvers.find((item) => item.id === evaluation.maneuverId) ?? { id: evaluation.maneuverId, code: evaluation.maneuverId, name: 'Maniobra', description: '', operationId: '' }, grade: evaluation.grade, observation: evaluation.observation, evidenceName: evaluation.evidenceName }))); this.loading.set(false); }, error: () => { this.error.set('No hemos podido cargar la misión.'); this.loading.set(false); } }); }
  person(): string { const item = this.assignment(); const user = item?.studentId ? this.users().find((entry) => entry.id === item.studentId) : null; return item?.externalPerson ?? (user ? `${user.firstName} ${user.lastName}` : 'Alumno'); }
  setResult(value: string): void { this.form.controls.result.setValue(value as MissionResult); }
  instructor(): string { const id = this.assignment()?.instructorId; const user = id ? this.users().find((entry) => entry.id === id) : null; return user ? `${user.firstName} ${user.lastName}` : 'Sin instructor'; }
  setGrade(id: string, value: string): void { this.rows.update((rows) => rows.map((row) => row.maneuver.id === id ? { ...row, grade: value as ManeuverGrade } : row)); }
  setObservation(id: string, value: string): void { this.rows.update((rows) => rows.map((row) => row.maneuver.id === id ? { ...row, observation: value } : row)); }
  toggle(id: string): void { this.openManeuver.update((current) => current === id ? null : id); }
  statusStep(): number { const status = this.execution()?.status; return status === 'completed' ? 3 : status === 'in-progress' ? 2 : 1; }
  async start(): Promise<void> { const current = this.execution(); if (!current || current.status !== 'scheduled') return; const now = new Date(); this.form.controls.startDate.setValue(now.toISOString().slice(0, 10)); this.form.controls.startTime.setValue(`${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`); await this.save('in-progress', 'Misión iniciada'); }
  calculateHours(): void { const start = this.toMinutes(this.form.controls.takeoffTime.value); const end = this.toMinutes(this.form.controls.landingTime.value); if (start === null || end === null || end <= start) return; this.form.controls.executedHours.setValue(Number(((end - start) / 60).toFixed(2)), { emitEvent: false }); }
  private toMinutes(value: string): number | null { const match = /^(\d{1,2}):(\d{2})$/.exec(value); if (!match) return null; return Number(match[1]) * 60 + Number(match[2]); }
  async close(): Promise<void> { if (!this.canClose()) { this.error.set('Existen maniobras pendientes por evaluar o faltan horas registradas.'); return; } await this.save('completed', 'Misión finalizada'); }
  async save(status = this.execution()?.status ?? 'scheduled', message = 'Cambios guardados'): Promise<void> { const current = this.execution(); if (!current) return; this.saving.set(true); this.error.set(null); const value = this.form.getRawValue(); const input: MissionExecutionWriteInput = { ...value, status: status as 'scheduled' | 'in-progress' | 'completed', result: value.result, evaluations: this.rows().map((row) => ({ id: `evaluation-${row.maneuver.id}`, maneuverId: row.maneuver.id, grade: row.grade, observation: row.observation, evidenceName: row.evidenceName })) }; try { const updated = await firstValueFrom(this.updateExecution.execute(current.id, input)); this.execution.set(updated); this.toast.success(message, 'La misión ya está actualizada.'); if (status === 'completed') await this.router.navigate(['/catalogo/ejecucion-misiones']); } catch (err: unknown) { const copy = err instanceof DomainError ? err.message : 'No hemos podido guardar la misión.'; this.error.set(copy); } finally { this.saving.set(false); } }
}
