import { NAV_ROUTES } from '@layout/navigation/data/nav-routes.constants';

export const MISSION_WORKSPACE_COPY = {
  back: 'Volver a la bandeja',
  saveDraft: 'Guardar borrador',
  save: 'Guardar',
  notesSaved: 'Notas de la maniobra guardadas',
  closeMission: 'Cerrar misión',
  reportIncident: 'Reportar incidencia',
  postponeTitle: 'Reportar incidencia',
  postponeMessage:
    '¿Se postergará el vuelo? Si se posterga, se cierra la misión y se limpian los datos ya cargados en esta hoja.',
  postponeYes: 'Sí, postergar y cerrar',
  postponeNo: 'No, continuar el reporte',
  postponed: 'Misión postergada',
  postponedLead: 'Se limpiaron los datos de la hoja y la misión quedó cerrada.',
  start: 'Iniciar misión',
  signaturesTitle: 'Firmas de cierre',
  signInstructor: 'Firma del instructor',
  signStudent: 'Firma del alumno',
  signCta: 'Firmar',
  signed: 'Firmado',
  pendingSignature: 'Pendiente de firma',
  counselQuestion: '¿Requiere consejo?',
  counselSaved: 'Se registró la solicitud de consejo.',
  signatureApplied: 'Firma registrada',
  loadError: 'No hemos podido cargar la misión.',
  saveError: 'No hemos podido guardar la misión.',
  closeError: 'Completa la evaluación, las horas y las firmas antes de cerrar la misión.',
  saved: 'Cambios guardados',
  started: 'Misión iniciada',
  closed: 'Misión finalizada',
  sheetKicker: 'Hoja de calificación operativa',
  pageTitle: 'Hoja de calificación operativa',
  pageLead: 'Califica las maniobras, registra el debriefing y cierra la misión.',
  historyLabel: 'Historial',
  currentMission: 'Actual',
  studentLabel: 'Alumno piloto',
  instructorLabel: 'Instructor evaluador',
  aircraftLabel: 'Aeronave / matrícula',
  dateLabel: 'Fecha y tiempo real',
  hoursSuffix: 'h calzo a calzo',
  maneuversTitle: 'Maniobras y procedimientos',
  maneuversLead: 'Califica cada maniobra. P desaprueba la misión.',
  expectedStandard: 'Estándar esperado',
  scaleLabel: 'Escala',
  deltaLabel: 'Desvío respecto al estándar',
  corLabel: 'COR',
  expand: 'Desplegar detalle',
  collapse: 'Ocultar detalle',
  causeLabel: 'Causa',
  observationLabel: 'Observación',
  recommendationLabel: 'Recomendación',
  causePlaceholder: 'Registre la causa de la desviación...',
  observationPlaceholder: 'Detalle de la ejecución...',
  recommendationPlaceholder: 'Recomendaciones para el alumno...',
  commentsTitle: 'Comentarios generales',
  commentsLead: 'Registra directrices para la siguiente sesión.',
  scoreTitle: 'Dictamen de calificación',
  scoreUnit: '/ 20',
  evaluatedLabel: 'Maniobras evaluadas',
  hoursLabel: 'Horas registradas',
  failedBanner: 'La misión queda desaprobada porque hay una calificación P.',
  pending: 'Pendiente',
  none: '—',
  phase: {
    scheduled: 'Programada',
    'in-progress': 'En debriefing',
    completed: 'Cerrada',
  },
  results: {
    approved: 'Aprobado',
    'approved-observations': 'Aprobado con observaciones',
    reinforcement: 'Requiere refuerzo',
    failed: 'Desaprobado',
  },
  grades: {
    P: 'Peligroso',
    D: 'Deficiente',
    I: 'Insuficiente',
    R: 'Regular',
    B: 'Bueno',
    E: 'Excelente',
  },
} as const;

export const MISSION_WORKSPACE_INBOX = NAV_ROUTES.missionExecution;
