export const PERSONNEL_DOSSIER_ROUTES = {
  list: '/catalogo/legajo-personal',
  detail: (userId: string) => `/catalogo/legajo-personal/${userId}`,
  program: (userId: string, programId: string) => `/catalogo/legajo-personal/${userId}/programa/${programId}`,
} as const;

export const PERSONNEL_DOSSIER_COPY = {
  listLead: 'Consulta el expediente digital de cada alumno: bitácora, horas y habilitaciones derivadas del catálogo.',
  searchLabel: 'Buscador',
  searchPlaceholder: 'Buscar por nombre, indicativo o documento',
  tableHeading: 'Tablero de expedientes',
  summaryPeople: 'Alumnos',
  summaryHours: 'Horas de bitácora',
  summaryAtRisk: 'En umbral de consejo',
  atRisk: 'Requiere consejo',
  openFile: 'Abrir expediente',
  cardBrand: 'SIGA',
  cardOrg: 'Sistema Integral de Gestión Académica',
  cardTitle: 'Carné de identificación',
  cardGrade: 'Grado',
  cardSurnames: 'Apellidos',
  cardNames: 'Nombres',
  cardNsa: 'N.S.A.',
  cardId: 'Documento',
  cardCallsign: 'Indicativo',
  cardSituation: 'Situación',
  cardSituationActive: 'Actividad',
  cardSituationInactive: 'Inactivo',
  cardExpiry: 'Caducidad',
  pagerPerPage: 'Por página:',
  pagerPerPageLabel: 'Tarjetas por página',
  tableCaption: 'Expedientes personales del contexto operativo',
  colStudent: 'Alumno',
  colIndicative: 'Indicativo',
  colDocument: 'Documento',
  colProgram: 'Programa',
  colHours: 'Horas',
  colAverage: 'Promedio',
  colStatus: 'Estado',
  empty: 'No hay legajos en este contexto.',
  loadError: 'No hemos podido cargar los legajos. Recarga la página.',
  needsSquadron: 'Selecciona un escuadrón en el encabezado para consultar los legajos.',
  view: 'Ver legajo',
  openCouncil: 'Abrir consejo',
  back: 'Volver al listado',
  watermark: 'Expediente digital centralizado',
  identity: 'Identidad',
  document: 'Documento',
  promotion: 'Promoción',
  specialty: 'Especialidad',
  statusActive: 'En servicio activo',
  unit: 'Unidad',
  squadron: 'Escuadrón',
  hoursTitle: 'Horas de vuelo acumuladas',
  hoursCut: 'Corte según bitácora de misiones completadas',
  hoursTotal: 'Horas totales',
  hoursDual: 'Doble comando',
  hoursNight: 'Nocturno',
  hoursIfr: 'Instrumentos',
  hoursUnit: 'h',
  tabLog: 'Bitácora y calificaciones',
  tabLicenses: 'Habilitaciones',
  tabIncidents: 'Incidencias y chequeos',
  tabRulings: 'Dictámenes y reconocimientos',
  chartTitle: 'Trayectoria de calificación',
  chartLead: 'Promedio de maniobras por misión (escala 0-20)',
  logTitle: 'Historial de misiones',
  logFilter: 'Filtrar misión, aeronave o instructor',
  colDate: 'Fecha',
  colMission: 'Misión',
  colAircraft: 'Aeronave',
  colInstructor: 'Instructor',
  colTime: 'Tiempo',
  colScore: 'Calificación',
  colSign: 'Firma',
  signed: 'Firmado',
  unsigned: 'Pendiente',
  licensesTitle: 'Habilitaciones y vigencias',
  licensesLead: 'Estado derivado de la matrícula y de las horas registradas.',
  rulingsTitle: 'Dictámenes y novedades',
  none: '—',
  councilBanner: 'Este alumno superó el tope de misiones reprobadas y puede elevarse a consejo de evaluación.',
  status: {
    'in-progress': 'En curso',
    completed: 'Culminado',
    suspended: 'Suspendido',
  },
  licenseStatus: {
    current: 'Vigente',
    approved: 'Aprobado',
    pending: 'Pendiente',
  },
  result: {
    approved: 'Aprobado',
    'approved-observations': 'Aprobado con observaciones',
    reinforcement: 'Refuerzo',
    failed: 'Desaprobado',
  },
  programsTitle: 'Programas de formación',
  programsLead: 'Cada programa se abre con su póster. Entra para ver fases, subfases y calificaciones de misión.',
  openProgram: 'Ver currículo',
  noPrograms: 'Este alumno aún no tiene programas en el expediente.',
  curriculumBack: 'Volver al expediente',
  curriculumKicker: 'Currículo del programa',
  phaseAccredited: 'Fase acreditada',
  phaseInProgress: 'Fase en curso',
  missionsWord: 'misiones',
  evaluatedWord: 'evaluadas',
  subphaseDone: 'Subfase culminada',
  subphaseOpen: 'Subfase en curso',
  subphaseAverage: 'Promedio subfase',
  flownWord: 'volada',
  foldersTitle: 'Carpetas del expediente',
  foldersCount: 'secciones oficiales',
  folderGrid: 'Cuadrícula',
  folderList: 'Lista',
  folderData: 'Datos y nombramientos',
  folderFlight: 'Récord de vuelo',
  folderGrades: 'Calificaciones',
  folderLicenses: 'Habilitaciones',
  folderPrograms: 'Cursos y programas',
  folderRulings: 'Dictámenes',
  folderFolios: 'folios',
  foliosTitle: 'Folios digitalizados recientes',
  folioSearch: 'Buscar por folio, misión o documento',
  folioDownload: 'Descargar',
  aircraftTitle: 'Aeronave asignada',
  aircraftSpec: 'Especificación técnica',
  aircraftHours: 'Horas en bitácora',
  kpiFlight: 'Vuelo',
  kpiLicense: 'Habilitación',
  kpiFile: 'Expediente',
  kpiNight: 'Nocturno',
  signAction: 'Firmar registro',
  downloadAction: 'Descargar PDF',
  signToast: 'Las firmas se registran en la hoja de calificación aérea.',
  downloadToast: 'La descarga del expediente se habilitará con el servicio de documentos.',
  analyticsTitle: 'Analítica descriptiva y soporte de mando',
  analyticsLead: 'Progreso curricular, bitácora, red de instrucción y trayectoria de calificación.',
  metricProgress: 'Progresión curricular',
  metricAverage: 'Índice ponderado',
  metricSigned: 'Readiness de firma',
  metricHours: 'Horas asignadas',
  metricGoal: 'Meta 100%',
  hoursRemaining: 'Faltante estimado',
  failedMissions: 'Misiones desaprobadas',
  projectionTitle: 'Proyección de cierre',
  projectionLead: 'Avance del programa actual',
  projectionRing: 'Avance',
  chartScale: 'Escala vigesimal 0-20',
  chartMission: 'Nota misión',
  chartAverage: 'Promedio',
  chartPass: 'Umbral 13',
  peakNote: 'Mejor nota histórica',
  instructorsTitle: 'Red de instrucción y tutores',
  instructorsLead: 'Horas recibidas según bitácora',
  pendingTitle: 'Pendientes de firma',
  pendingEmpty: 'No hay misiones pendientes de firma en bitácora.',
  noAircraft: 'Sin aeronave en bitácora',
  opsActive: 'En instrucción',
} as const;
