export const PROFILE_CONTEXT_COPY = {
  brandName: 'SIGA',
  brandUnit: 'Sistema Integral de Gestión Académica',
  title: 'Selecciona tu contexto de trabajo',
  subtitle: 'Selecciona la unidad y/o escuadrón donde deseas operar dentro del sistema.',
  auditTitle: 'Contexto de consulta',
  auditSubtitle:
    'Tu perfil de auditoría no opera sobre una unidad o escuadrón concreto. Continúa para revisar la información con alcance de consulta.',
  lockedTitle: 'Confirma tu contexto operativo',
  lockedSubtitle: 'Tu unidad y escuadrón vienen determinados por tu asignación. Continúa para entrar al sistema.',
  unitLabel: 'Unidades',
  squadronLabel: 'Escuadrones',
  unitPlaceholder: 'Seleccionar unidad',
  squadronPlaceholder: 'Seleccionar escuadrón',
  allSquadrons: 'Todos los escuadrones',
  allSquadronsCaption: 'Operar sobre la unidad completa',
  backToUnits: 'Cambiar unidad',
  chooseSquadron: 'Elegir escuadrón',
  squadronModalTitle: 'Selecciona un escuadrón',
  continue: 'Continuar',
  loadingTitle: 'Preparando perfilamiento',
  loadingSubtitle: 'Cargamos las unidades y escuadrones disponibles para tu rol.',
  emptySquadrons: 'Esta unidad no tiene escuadrones activos.',
  loadError: 'No hemos podido cargar el perfilamiento. Inténtalo de nuevo.',
  contextHeading: 'Contexto operativo',
  assignedUnit: 'Unidad asignada',
  assignedSquadron: 'Escuadrón asignado',
  none: 'Sin asignar',
} as const;
