import { Provider } from '@angular/core';
import {
  CalculateLoanInstallment,
  CalculateMortgageInstallment,
  ChangeUserPassword,
  CreateAdminUser,
  GetAdminUser,
  CreateSpecialty,
  CreateUserRole,
  GetAccounts,
  GetCurrentUser,
  GetCards,
  GetFaqs,
  GetFeaturedProducts,
  GetHelpTopics,
  GetAcademicRecord,
  GetDashboardOverview,
  GetOperationalReport,
  GetHomeContent,
  GetInvestmentProducts,
  GetLoans,
  GetMortgages,
  GetProductsByNeed,
  GetPromotions,
  CreateAircraft,
  CreateFleet,
  CreateManeuver,
  CreateMissionType,
  CreateOperation,
  CreatePhaseBank,
  CreateSubphaseBank,
  CreateSquadron,
  CreateStandard,
  CreateTemporaryCommission,
  CreateUnit,
  CreateWeighting,
  ListAdminUsers,
  ListAcademicProgress,
  ListPromotions,
  CreatePromotion,
  UpdatePromotion,
  ListPromotionMembers,
  SavePromotionMembers,
  ListProgramEnrollments,
  EnrollInProgram,
  CloseProgramEnrollment,
  GetProgrammingBoard,
  GetDailyDispatchBoard,
  GetFlightOrderBoard,
  IssueFlightOrder,
  AssignGroundCourses,
  StartMissionDispatch,
  CancelDispatchSlot,
  ListGroupAssignments,
  CreateGroupAssignment,
  UpdateGroupAssignment,
  ListIndividualAssignments,
  CreateIndividualAssignment,
  UpdateIndividualAssignment,
  ListMissionExecutions,
  GetMissionExecution,
  UpdateMissionExecution,
  ListAircraft,
  ListFleets,
  ListManeuvers,
  ListMissionTypes,
  ListOperations,
  ListPhaseBanks,
  ListPhases,
  ListPrograms,
  ListSubphaseBanks,
  ListSubphases,
  ListSquadrons,
  ListSpecialties,
  ListStandards,
  ListTemporaryCommissions,
  ListUnits,
  ListWeightings,
  ListUserRoles,
  UpdateAdminUser,
  UpdateSpecialty,
  UpdateUserAddress,
  UpdateUserContact,
  UpdateUserPhoto,
  UpdateUserPreferences,
  UpdateUserProfile,
  UpdateAircraft,
  UpdateFleet,
  UpdateManeuver,
  UpdateMissionType,
  UpdateOperation,
  UpdatePhaseBank,
  UpdateSubphaseBank,
  UpdateSquadron,
  UpdateStandard,
  UpdateTemporaryCommission,
  UpdateUnit,
  AssignProgramStandards,
  AuthenticateUser,
  ConfirmProfileContext,
  GetProfileContext,
  SaveProgramCurriculum,
  SaveProgramStandardMatrix,
  UpdateWeighting,
  UpdateUserRole,
} from '../application';
import { MockAccountRepository } from '../adapters/mock/mock-account.repository';
import { MockAdminCatalogRepository } from '../adapters/mock/mock-admin-catalog.repository';
import { MockAuthRepository } from '../adapters/mock/mock-auth.repository';
import { MockCardRepository } from '../adapters/mock/mock-card.repository';
import { MockFaqRepository } from '../adapters/mock/mock-faq.repository';
import { MockInvestmentRepository } from '../adapters/mock/mock-investment.repository';
import { MockLoanRepository } from '../adapters/mock/mock-loan.repository';
import { MockProductRepository } from '../adapters/mock/mock-product.repository';
import { MockPromotionRepository } from '../adapters/mock/mock-promotion.repository';
import { MockUserProfileRepository } from '../adapters/mock/mock-user.repository';
import type {
  AccountRepository,
  AdminCatalogRepository,
  AuthRepository,
  CardRepository,
  FaqRepository,
  InvestmentRepository,
  LoanRepository,
  ProductRepository,
  PromotionRepository,
  UserProfileRepository,
} from '../ports';
import {
  ACCOUNT_REPOSITORY,
  ADMIN_CATALOG_REPOSITORY,
  AUTH_REPOSITORY,
  CARD_REPOSITORY,
  FAQ_REPOSITORY,
  INVESTMENT_REPOSITORY,
  LOAN_REPOSITORY,
  PRODUCT_REPOSITORY,
  PROMOTION_REPOSITORY,
  USER_PROFILE_REPOSITORY,
} from './tokens';

export const CORE_PROVIDERS: Provider[] = [
  { provide: PRODUCT_REPOSITORY, useClass: MockProductRepository },
  { provide: PROMOTION_REPOSITORY, useClass: MockPromotionRepository },
  { provide: ACCOUNT_REPOSITORY, useClass: MockAccountRepository },
  { provide: CARD_REPOSITORY, useClass: MockCardRepository },
  { provide: LOAN_REPOSITORY, useClass: MockLoanRepository },
  { provide: INVESTMENT_REPOSITORY, useClass: MockInvestmentRepository },
  { provide: FAQ_REPOSITORY, useClass: MockFaqRepository },
  { provide: USER_PROFILE_REPOSITORY, useClass: MockUserProfileRepository },
  { provide: ADMIN_CATALOG_REPOSITORY, useClass: MockAdminCatalogRepository },
  { provide: AUTH_REPOSITORY, useClass: MockAuthRepository },
  {
    provide: AuthenticateUser,
    useFactory: (repo: AuthRepository) => new AuthenticateUser(repo),
    deps: [AUTH_REPOSITORY],
  },
  {
    provide: GetProfileContext,
    useFactory: (repo: AdminCatalogRepository) => new GetProfileContext(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ConfirmProfileContext,
    useFactory: (repo: AdminCatalogRepository) => new ConfirmProfileContext(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  { provide: CalculateLoanInstallment, useFactory: () => new CalculateLoanInstallment() },
  { provide: CalculateMortgageInstallment, useFactory: () => new CalculateMortgageInstallment() },
  {
    provide: GetFeaturedProducts,
    useFactory: (repo: ProductRepository) => new GetFeaturedProducts(repo),
    deps: [PRODUCT_REPOSITORY],
  },
  {
    provide: GetPromotions,
    useFactory: (repo: PromotionRepository) => new GetPromotions(repo),
    deps: [PROMOTION_REPOSITORY],
  },
  {
    provide: GetAccounts,
    useFactory: (repo: AccountRepository) => new GetAccounts(repo),
    deps: [ACCOUNT_REPOSITORY],
  },
  {
    provide: GetCards,
    useFactory: (repo: CardRepository) => new GetCards(repo),
    deps: [CARD_REPOSITORY],
  },
  {
    provide: GetLoans,
    useFactory: (repo: LoanRepository) => new GetLoans(repo),
    deps: [LOAN_REPOSITORY],
  },
  {
    provide: GetMortgages,
    useFactory: (repo: LoanRepository) => new GetMortgages(repo),
    deps: [LOAN_REPOSITORY],
  },
  {
    provide: GetInvestmentProducts,
    useFactory: (repo: InvestmentRepository) => new GetInvestmentProducts(repo),
    deps: [INVESTMENT_REPOSITORY],
  },
  {
    provide: GetFaqs,
    useFactory: (repo: FaqRepository) => new GetFaqs(repo),
    deps: [FAQ_REPOSITORY],
  },
  {
    provide: GetHelpTopics,
    useFactory: (repo: FaqRepository) => new GetHelpTopics(repo),
    deps: [FAQ_REPOSITORY],
  },
  {
    provide: GetProductsByNeed,
    useFactory: (repo: ProductRepository) => new GetProductsByNeed(repo),
    deps: [PRODUCT_REPOSITORY],
  },
  {
    provide: GetCurrentUser,
    useFactory: (repo: UserProfileRepository) => new GetCurrentUser(repo),
    deps: [USER_PROFILE_REPOSITORY],
  },
  {
    provide: UpdateUserProfile,
    useFactory: (repo: UserProfileRepository) => new UpdateUserProfile(repo),
    deps: [USER_PROFILE_REPOSITORY],
  },
  {
    provide: UpdateUserContact,
    useFactory: (repo: UserProfileRepository) => new UpdateUserContact(repo),
    deps: [USER_PROFILE_REPOSITORY],
  },
  {
    provide: UpdateUserAddress,
    useFactory: (repo: UserProfileRepository) => new UpdateUserAddress(repo),
    deps: [USER_PROFILE_REPOSITORY],
  },
  {
    provide: UpdateUserPhoto,
    useFactory: (repo: UserProfileRepository) => new UpdateUserPhoto(repo),
    deps: [USER_PROFILE_REPOSITORY],
  },
  {
    provide: UpdateUserPreferences,
    useFactory: (repo: UserProfileRepository) => new UpdateUserPreferences(repo),
    deps: [USER_PROFILE_REPOSITORY],
  },
  {
    provide: ChangeUserPassword,
    useFactory: (repo: UserProfileRepository) => new ChangeUserPassword(repo),
    deps: [USER_PROFILE_REPOSITORY],
  },
  {
    provide: GetAdminUser,
    useFactory: (repo: AdminCatalogRepository) => new GetAdminUser(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListAdminUsers,
    useFactory: (repo: AdminCatalogRepository) => new ListAdminUsers(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListPromotions,
    useFactory: (repo: AdminCatalogRepository) => new ListPromotions(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreatePromotion,
    useFactory: (repo: AdminCatalogRepository) => new CreatePromotion(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdatePromotion,
    useFactory: (repo: AdminCatalogRepository) => new UpdatePromotion(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListPromotionMembers,
    useFactory: (repo: AdminCatalogRepository) => new ListPromotionMembers(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: SavePromotionMembers,
    useFactory: (repo: AdminCatalogRepository) => new SavePromotionMembers(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListProgramEnrollments,
    useFactory: (repo: AdminCatalogRepository) => new ListProgramEnrollments(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: EnrollInProgram,
    useFactory: (repo: AdminCatalogRepository) => new EnrollInProgram(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CloseProgramEnrollment,
    useFactory: (repo: AdminCatalogRepository) => new CloseProgramEnrollment(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: GetProgrammingBoard,
    useFactory: (repo: AdminCatalogRepository) => new GetProgrammingBoard(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: GetDailyDispatchBoard,
    useFactory: (repo: AdminCatalogRepository) => new GetDailyDispatchBoard(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: GetFlightOrderBoard,
    useFactory: (repo: AdminCatalogRepository) => new GetFlightOrderBoard(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: IssueFlightOrder,
    useFactory: (repo: AdminCatalogRepository) => new IssueFlightOrder(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: AssignGroundCourses,
    useFactory: (repo: AdminCatalogRepository) => new AssignGroundCourses(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: StartMissionDispatch,
    useFactory: (repo: AdminCatalogRepository) => new StartMissionDispatch(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CancelDispatchSlot,
    useFactory: (repo: AdminCatalogRepository) => new CancelDispatchSlot(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  { provide: ListGroupAssignments, useFactory: (repo: AdminCatalogRepository) => new ListGroupAssignments(repo), deps: [ADMIN_CATALOG_REPOSITORY] },
  { provide: CreateGroupAssignment, useFactory: (repo: AdminCatalogRepository) => new CreateGroupAssignment(repo), deps: [ADMIN_CATALOG_REPOSITORY] },
  { provide: UpdateGroupAssignment, useFactory: (repo: AdminCatalogRepository) => new UpdateGroupAssignment(repo), deps: [ADMIN_CATALOG_REPOSITORY] },
  { provide: ListIndividualAssignments, useFactory: (repo: AdminCatalogRepository) => new ListIndividualAssignments(repo), deps: [ADMIN_CATALOG_REPOSITORY] },
  { provide: CreateIndividualAssignment, useFactory: (repo: AdminCatalogRepository) => new CreateIndividualAssignment(repo), deps: [ADMIN_CATALOG_REPOSITORY] },
  { provide: UpdateIndividualAssignment, useFactory: (repo: AdminCatalogRepository) => new UpdateIndividualAssignment(repo), deps: [ADMIN_CATALOG_REPOSITORY] },
  { provide: ListMissionExecutions, useFactory: (repo: AdminCatalogRepository) => new ListMissionExecutions(repo), deps: [ADMIN_CATALOG_REPOSITORY] },
  { provide: GetMissionExecution, useFactory: (repo: AdminCatalogRepository) => new GetMissionExecution(repo), deps: [ADMIN_CATALOG_REPOSITORY] },
  { provide: UpdateMissionExecution, useFactory: (repo: AdminCatalogRepository) => new UpdateMissionExecution(repo), deps: [ADMIN_CATALOG_REPOSITORY] },
  {
    provide: CreateAdminUser,
    useFactory: (repo: AdminCatalogRepository) => new CreateAdminUser(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateAdminUser,
    useFactory: (repo: AdminCatalogRepository) => new UpdateAdminUser(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListUserRoles,
    useFactory: (repo: AdminCatalogRepository) => new ListUserRoles(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateUserRole,
    useFactory: (repo: AdminCatalogRepository) => new CreateUserRole(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateUserRole,
    useFactory: (repo: AdminCatalogRepository) => new UpdateUserRole(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListSpecialties,
    useFactory: (repo: AdminCatalogRepository) => new ListSpecialties(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateSpecialty,
    useFactory: (repo: AdminCatalogRepository) => new CreateSpecialty(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateSpecialty,
    useFactory: (repo: AdminCatalogRepository) => new UpdateSpecialty(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListUnits,
    useFactory: (repo: AdminCatalogRepository) => new ListUnits(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateUnit,
    useFactory: (repo: AdminCatalogRepository) => new CreateUnit(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateUnit,
    useFactory: (repo: AdminCatalogRepository) => new UpdateUnit(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListSquadrons,
    useFactory: (repo: AdminCatalogRepository) => new ListSquadrons(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateSquadron,
    useFactory: (repo: AdminCatalogRepository) => new CreateSquadron(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateSquadron,
    useFactory: (repo: AdminCatalogRepository) => new UpdateSquadron(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListTemporaryCommissions,
    useFactory: (repo: AdminCatalogRepository) => new ListTemporaryCommissions(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateTemporaryCommission,
    useFactory: (repo: AdminCatalogRepository) => new CreateTemporaryCommission(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateTemporaryCommission,
    useFactory: (repo: AdminCatalogRepository) => new UpdateTemporaryCommission(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListOperations,
    useFactory: (repo: AdminCatalogRepository) => new ListOperations(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateOperation,
    useFactory: (repo: AdminCatalogRepository) => new CreateOperation(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateOperation,
    useFactory: (repo: AdminCatalogRepository) => new UpdateOperation(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListMissionTypes,
    useFactory: (repo: AdminCatalogRepository) => new ListMissionTypes(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateMissionType,
    useFactory: (repo: AdminCatalogRepository) => new CreateMissionType(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateMissionType,
    useFactory: (repo: AdminCatalogRepository) => new UpdateMissionType(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListManeuvers,
    useFactory: (repo: AdminCatalogRepository) => new ListManeuvers(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateManeuver,
    useFactory: (repo: AdminCatalogRepository) => new CreateManeuver(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateManeuver,
    useFactory: (repo: AdminCatalogRepository) => new UpdateManeuver(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListStandards,
    useFactory: (repo: AdminCatalogRepository) => new ListStandards(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateStandard,
    useFactory: (repo: AdminCatalogRepository) => new CreateStandard(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateStandard,
    useFactory: (repo: AdminCatalogRepository) => new UpdateStandard(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListWeightings,
    useFactory: (repo: AdminCatalogRepository) => new ListWeightings(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateWeighting,
    useFactory: (repo: AdminCatalogRepository) => new CreateWeighting(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateWeighting,
    useFactory: (repo: AdminCatalogRepository) => new UpdateWeighting(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListFleets,
    useFactory: (repo: AdminCatalogRepository) => new ListFleets(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateFleet,
    useFactory: (repo: AdminCatalogRepository) => new CreateFleet(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateFleet,
    useFactory: (repo: AdminCatalogRepository) => new UpdateFleet(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListAircraft,
    useFactory: (repo: AdminCatalogRepository) => new ListAircraft(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateAircraft,
    useFactory: (repo: AdminCatalogRepository) => new CreateAircraft(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateAircraft,
    useFactory: (repo: AdminCatalogRepository) => new UpdateAircraft(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListPrograms,
    useFactory: (repo: AdminCatalogRepository) => new ListPrograms(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListPhases,
    useFactory: (repo: AdminCatalogRepository) => new ListPhases(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListSubphases,
    useFactory: (repo: AdminCatalogRepository) => new ListSubphases(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListPhaseBanks,
    useFactory: (repo: AdminCatalogRepository) => new ListPhaseBanks(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreatePhaseBank,
    useFactory: (repo: AdminCatalogRepository) => new CreatePhaseBank(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdatePhaseBank,
    useFactory: (repo: AdminCatalogRepository) => new UpdatePhaseBank(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListSubphaseBanks,
    useFactory: (repo: AdminCatalogRepository) => new ListSubphaseBanks(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: CreateSubphaseBank,
    useFactory: (repo: AdminCatalogRepository) => new CreateSubphaseBank(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: UpdateSubphaseBank,
    useFactory: (repo: AdminCatalogRepository) => new UpdateSubphaseBank(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: SaveProgramCurriculum,
    useFactory: (repo: AdminCatalogRepository) => new SaveProgramCurriculum(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: AssignProgramStandards,
    useFactory: (repo: AdminCatalogRepository) => new AssignProgramStandards(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: SaveProgramStandardMatrix,
    useFactory: (repo: AdminCatalogRepository) => new SaveProgramStandardMatrix(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: GetHomeContent,
    useFactory: (products: ProductRepository, promotions: PromotionRepository, faqs: FaqRepository) =>
      new GetHomeContent(products, promotions, faqs),
    deps: [PRODUCT_REPOSITORY, PROMOTION_REPOSITORY, FAQ_REPOSITORY],
  },
  {
    provide: GetDashboardOverview,
    useFactory: (repo: AdminCatalogRepository) => new GetDashboardOverview(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: ListAcademicProgress,
    useFactory: (repo: AdminCatalogRepository) => new ListAcademicProgress(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: GetAcademicRecord,
    useFactory: (repo: AdminCatalogRepository) => new GetAcademicRecord(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
  {
    provide: GetOperationalReport,
    useFactory: (repo: AdminCatalogRepository) => new GetOperationalReport(repo),
    deps: [ADMIN_CATALOG_REPOSITORY],
  },
];
