export const ACADEMIC_PROGRESS_ROUTES = {
  list: '/catalogo/avance-academico',
  detail: (userId: string) => `/catalogo/avance-academico/${userId}`,
} as const;

export const ACADEMIC_PROGRESS_COPY = {
  listLead:
    'Consulta el avance y la trayectoria de los alumnos visibles en tu unidad y escuadrón de trabajo.',
  searchLabel: 'Buscador',
  searchPlaceholder: 'Buscar por nombre o indicativo',
  tableHeading: 'Avance por alumno',
  tableCaption: 'Alumnos con trayectoria académica en el contexto operativo',
  colStudent: 'Alumno',
  colIndicative: 'Indicativo',
  colProgram: 'Programa actual',
  colProgress: 'Avance',
  colAverage: 'Promedio',
  colStatus: 'Estado académico',
  empty: 'No hay alumnos con avance en este contexto.',
  loadError: 'No hemos podido cargar el avance académico. Recarga la página.',
  needsSquadron:
    'Selecciona un escuadrón en el encabezado para consultar el avance. La pantalla reutiliza el contexto de unidad y escuadrón; no se pide de nuevo aquí.',
  view: 'Ver trayectoria',
  back: 'Volver al listado',
  currentEyebrow: 'Progreso académico',
  currentTitle: 'Situación actual',
  programLabel: 'Programa',
  progressLabel: 'Avance académico',
  phaseLabel: 'Fase actual',
  subphaseLabel: 'Subfase actual',
  instructorLabel: 'Instructor',
  specialtyLabel: 'Especialidad',
  rankLabel: 'Puesto en el programa',
  graderLabel: 'Calificó',
  resultLabel: 'Resultado',
  yearLabel: 'Año académico',
  lifecycleLabel: 'Plan de estudios',
  lifecycleCulminated: 'Culminado',
  lifecycleOpen: 'Abierto',
  completedLabel: 'Misiones completadas',
  pendingLabel: 'Misiones pendientes',
  hoursLabel: 'Horas acumuladas',
  averageLabel: 'Promedio',
  statusLabel: 'Estado académico',
  enrollmentLabel: 'Estado de matrícula',
  promotionLabel: 'Promoción',
  noPromotion: 'Sin promoción',
  closedAtLabel: 'Fecha de baja',
  closeReasonLabel: 'Motivo',
  blockedWrite: 'No se pueden asignar misiones, programar evaluaciones ni avanzar de fase.',
  noCurrent: 'Este alumno no tiene un programa en curso.',
  historyTitle: 'Historial académico',
  historyLead: 'Selecciona un programa para ver fases, misiones, evaluaciones y certificaciones.',
  historyProgram: 'Programa',
  historyStatus: 'Estado',
  historyAverage: 'Promedio',
  historyHours: 'Horas',
  historyDates: 'Fechas',
  detailTitle: 'Detalle del programa',
  phasesDone: 'Fases realizadas',
  subphasesDone: 'Subfases realizadas',
  missionsDone: 'Misiones ejecutadas',
  evaluations: 'Evaluaciones',
  certifications: 'Certificaciones',
  finalStatus: 'Estado final',
  start: 'Inicio',
  end: 'Finalización',
  timelineTitle: 'Timeline académico',
  none: '—',
  resultApproved: 'Aprobado',
  resultFailed: 'Desaprobado',
  status: {
    'in-progress': 'En curso',
    completed: 'Aprobado',
    suspended: 'Desaprobado',
  },
  enrollmentStatus: {
    active: 'Activo',
    suspended: 'Suspendido',
    withdrawn: 'Retirado',
    dropped: 'Dado de baja',
    completed: 'Completado',
  },
  timeline: {
    'program-started': 'Programa iniciado',
    'phase-completed': 'Fase completada',
    evaluation: 'Evaluación intermedia',
    'phase-started': 'Fase iniciada',
    'program-current': 'Programa actual',
  },
  phaseCompletedSuffix: 'completada',
  phaseStartedSuffix: 'iniciada',
} as const;
