export const AIR_GRADE_ROUTES = {
  list: '/catalogo/calificaciones-aire',
  board: (userId: string, programId?: string) =>
    programId
      ? `/catalogo/calificaciones-aire/${userId}/programa/${programId}`
      : `/catalogo/calificaciones-aire/${userId}`,
  sheet: (userId: string, executionId: string) => `/catalogo/calificaciones-aire/${userId}/mision/${executionId}`,
} as const;

export const AIR_GRADE_COPY = {
  listLead: 'Elige un programa para ver tus misiones aéreas por fase y subfase, y corroborar el calificativo.',
  empty: 'No tienes programas de vuelo en tu expediente.',
  loadError: 'No hemos podido cargar las calificaciones de vuelo. Recarga la página.',
  viewProgress: 'Ver progresión',
  cardProgress: 'Avance',
  cardAverage: 'Promedio',
  cardHours: 'Horas',
  back: 'Volver al listado',
  backBoard: 'Volver a la progresión',
  sheetTitle: 'Cartilla de calificación de vuelo',
  sheetLead: 'Revisa el calificativo de la misión y firma de conformidad.',
  boardTitle: 'Progresión curricular de misiones',
  boardLead: 'Consulta las misiones aéreas por fase y subfase, con el calificativo vigesimal de cada vuelo.',
  none: '—',
  status: {
    'in-progress': 'En curso',
    completed: 'Aprobado',
    suspended: 'Desaprobado',
  },
  programBadge: 'Programa de formación',
  studentLabel: 'Alumno',
  indicativeLabel: 'Indicativo',
  unitLabel: 'Unidad / escuadrón',
  operationalLabel: 'Estado',
  operationalActive: 'Activo',
  operationalInactive: 'Inactivo',
  progressLabel: 'Avance del curso',
  averageLabel: 'Promedio general',
  hoursLabel: 'Horas voladas',
  missionsLabel: 'Misiones voladas',
  approvedSuffix: 'aprobadas',
  remainingHours: 'Restante',
  failedHint: 'con repetición requerida',
  outOf: '/',
  hoursUnit: 'hrs',
  phaseMissions: 'misiones',
  phaseEvaluated: 'evaluadas',
  phaseAccredited: 'Fase acreditada',
  subphaseDone: 'Subfase culminada',
  subphaseProgress: 'En progreso',
  subphaseAverage: 'Promedio subfase',
  flown: 'volada',
  pendingCount: 'pendientes',
  legendTitle: 'Leyenda de calificación',
  legendLead: 'Escala vigesimal de 00 a 20.',
  legendPass: 'Aprobado',
  legendPassRange: '16,0 – 20,0',
  legendRegular: 'Regular',
  legendRegularRange: '13,0 – 15,9',
  legendFail: 'Desaprobado',
  legendFailRange: 'Menor a 13,0',
  legendPending: 'Pendiente',
  legendPendingRange: 'Sin volar',
  legendCheck: 'Subfase culminada',
  hoursDistribution: 'Distribución de horas de vuelo',
  hoursTotal: 'Total',
  logTitle: 'Bitácora de vuelo',
  logOpen: 'Ver cartilla de calificación',
  tileStatuses: {
    pending: 'Programada',
    insufficient: 'Insuf.',
    observed: 'Observado',
    regular: 'Regular',
    approved: 'Aprobado',
    outstanding: 'Sobresal.',
  },
  actionRequired: 'Acción requerida',
  pendingReview: 'Pendiente de tu revisión y firma de conformidad para el cierre de la cartilla.',
  goSign: 'Ir a firmar',
  studentPilot: 'Alumno piloto',
  academicStatus: 'Situación académica',
  dateLabel: 'Fecha de ejecución',
  aircraftLabel: 'Aeronave / matrícula',
  flightTime: 'Tiempo de vuelo',
  instructorLabel: 'Instructor evaluador',
  dualHint: 'Tiempo de instrucción',
  verdictTitle: 'Dictamen de evaluación',
  official: 'Oficial',
  scaleMax: '/ 20,00',
  results: {
    approved: 'Aprobado',
    'approved-observations': 'Aprobado con observaciones',
    reinforcement: 'Refuerzo',
    failed: 'Desaprobado',
    pending: 'Pendiente',
  },
  thresholdLabel: 'Umbral aprobatorio: 13,00',
  thresholdShort: 'Umbral aprobatorio',
  deltaLabel: 'Delta',
  historyTitle: 'Historial comparativo de la subfase',
  currentMission: 'Actual',
  maneuversTitle: 'Maniobras y procedimientos',
  maneuversLead: 'Consulta cada maniobra. El detalle se despliega solo si hay COR.',
  corLabel: 'COR',
  scaleLabel: 'Escala',
  grades: {
    P: 'Peligroso',
    D: 'Deficiente',
    I: 'Insuficiente',
    R: 'Regular',
    B: 'Bueno',
    E: 'Excelente',
  },
  gradeE: 'E: Excelente',
  gradeB: 'B: Bueno',
  gradeR: 'R: Regular',
  technicalNote: 'Observación técnica',
  causeLabel: 'Causa',
  observationLabel: 'Observación',
  instructionLabel: 'Recomendación',
  commentsTitle: 'Comentarios generales',
  signInstructor: 'Firma del instructor',
  signStudent: 'Firma del alumno',
  signaturesTitle: 'Firmas de cierre',
  objection: 'Enviar inconformidad',
  objectionSent: 'Hemos registrado tu inconformidad. Ya no es necesario firmar esta cartilla.',
  objectionRecorded: 'Inconformidad enviada',
  objectionError: 'No hemos podido registrar la inconformidad. Inténtalo de nuevo.',
  noDebrief: 'El instructor no dejó comentarios en esta cartilla.',
  radarTitle: 'Distribución por criterio',
  signTitle: 'Conformidad del alumno',
  signLead: 'Certifica que has leído el debriefing y corrobora el calificativo.',
  conformityLabel:
    'He leído el debriefing de esta misión, comprendo las recomendaciones del instructor y declaro mi conformidad con la calificación registrada.',
  signCta: 'Firmar y asentar en el expediente',
  signPad: 'Firmar',
  signed: 'Firmado',
  pendingSignature: 'Pendiente de firma',
  clarify: 'Solicitar aclaración',
  clarifySent: 'Hemos registrado tu solicitud de aclaración con el instructor.',
  signHint: 'Al firmar, las horas de vuelo y la nota se acreditan en tu expediente de instrucción.',
  signedSuccess: 'Misión firmada y registrada',
  signedSuccessLead: 'La cartilla quedó asentada en tu expediente.',
  signatureDialog: 'Firma de conformidad',
  noPrograms: 'Este alumno no tiene misiones aéreas en su plan de estudios.',
  signError: 'No hemos podido registrar la firma. Inténtalo de nuevo.',
  alreadySigned: 'Esta cartilla ya está firmada.',
} as const;
