export const PROGRAM_STUDIO_COPY = {
  back: 'Volver a la academia',
  loading: 'Cargando el programa',
  loadingHint: 'Un momento.',
  saving: 'Guardando el programa',
  savingHint: 'Estamos guardando el programa en la academia.',
  loadError: 'No hemos podido cargar este programa.',
  crumbPrograms: 'Programas de instrucción',
  newCode: 'Nuevo programa',
  contextUnit: 'Unidad',
  contextSquadron: 'Escuadrón',
  hoursLoad: 'Carga curricular',
  hoursUnit: 'h',
  phasesMeta: 'fases',
  phaseMeta: 'fase',
  modulesTitle: 'Arquitectura del programa',
  expand: 'Expandir todo',
  collapse: 'Contraer',
  addPhase: 'Añadir fase al itinerario',
  moduleKicker: 'Itinerario',
  ofProgram: 'del programa',
  missionsWord: 'misiones',
  missionWord: 'misión',
  subphaseAction: 'Subfase',
  metricsKicker: 'Métricas del plan',
  metricsTitle: 'Resumen académico',
  totalHours: 'Horas tot.',
  ratioPhases: 'Fases del itinerario',
  ratioSubphases: 'Subfases',
  ratioMissions: 'Misiones de vuelo',
  progressionTitle: 'Requisitos de progresión',
  progressionLead:
    'El alumno avanza en el orden de las fases del programa. Completar una fase habilita la siguiente.',
  progressionLeadGround:
    'El alumno avanza en el orden de los cursos de tierra. Completar un curso habilita el siguiente.',
  firstPhaseGate: 'Fase inicial del itinerario. No tiene fase previa.',
  nextPhaseGate: 'Completar la fase anterior para habilitar esta etapa.',
  firstCourseGate: 'Curso inicial del itinerario de tierra. No tiene curso previo.',
  nextCourseGate: 'Completar el curso anterior para habilitar esta etapa.',
  continueMatrix: 'Continuar a matriz de instrucción',
  continueFlow: 'Ver flujo del programa',
  saveCopy: 'Guardar programa',
  create: 'Crear programa',
  cancel: 'Cancelar',
  culminatedBanner: (year: number | null) =>
    year === null
      ? 'Este programa está culminado. La calificación finalizó y no se puede modificar.'
      : `El programa de ${year} está culminado. La calificación finalizó y no se puede modificar.`,
  needsSquadron:
    'Selecciona un escuadrón en el encabezado para asociar el contexto operativo. Esta pantalla no vuelve a pedir la unidad.',
  none: '—',
  stepPlan: 'Diseñar plan de estudios',
  sectionLead: 'Programas de formación y planes de estudios.',
  calibratorTitle: 'Calibrador de celda',
  calibratorEmpty: 'Selecciona una celda de la matriz para definir el estándar.',
  calibratorGrade: 'Estándar requerido',
  calibratorPickHint: 'Pulsa una letra para fijar el mínimo de la maniobra. Vuelve a pulsarla para quitarla y dejar los puntajes en cero.',
  calibratorDeltaTitle: 'Puntajes DIRBEP',
  calibratorDeltaHint:
    'Pulsa más o menos en cada letra. El recuadro de sumar aparece al pulsar más. El de restar, cuando el ajuste es negativo. En peligroso, resta puntos o da de baja la misión.',
  calibratorAdd: 'Sumar',
  calibratorSub: 'Restar',
  calibratorPlus: 'Sumar un punto',
  calibratorMinus: 'Restar un punto',
  calibratorRequired: 'Requerido',
  calibratorDischarge: 'Dar de baja',
  calibratorApply: 'Actualizar regla de celda',
  calibratorTarget: 'Calificación objetivo',
  calibratorDangerGrade: 'Peligroso',
  matrixExpand: 'Ampliar pantalla',
  matrixCollapse: 'Salir de pantalla completa',
  stepModules: 'Módulos',
  stepArchitecture: 'Arquitectura de módulos',
  stepMatrix: 'Matriz',
  next: 'Continuar',
  prev: 'Atrás',
  planGate: 'Completa el código y el nombre del programa para continuar.',
  modulesGate: 'Activa al menos un módulo y marca cuál usar para continuar.',
  architectureGate: 'Cada módulo activo necesita al menos una fase con una subfase o un curso.',
  matrixGate: 'En aire y simulador, cada subfase necesita misiones y maniobras antes de guardar.',
  matrixEmpty: 'Este programa no tiene subfases de aire o simulador. Puedes guardar el plan de tierra.',
  matrixPick: 'Esta subfase aún no tiene misiones o maniobras. Asígnelas aquí para construir la matriz.',
  modulesLead: 'Activa uno, dos o los tres módulos. Marca el checkbox de avanzar en el que quieras continuar.',
  enableModule: 'Activo',
  advanceModule: 'Avanzar',
  architectureAir: 'Instrucción en aire',
  architectureSim: 'Simulador de vuelo',
  architectureGround: 'Instrucción en tierra',
  coursesHeading: 'Cursos',
  subjectsHeading: 'Asignaturas',
  courseKicker: 'Curso',
  editCourse: 'Editar curso',
  addCourse: 'Añadir asignatura',
  addCoursePath: 'Añadir curso al itinerario',
  addCourseLabel: 'Añadir curso',
  colCourse: 'Curso',
  colSubject: 'Asignatura',
  colHours: 'Horas',
  colCoefficient: 'Coef.',
  colMinGrade: 'Nota mín.',
  emptyGround: 'Añade el primer curso de tierra.',
  emptySubjects: 'Añade la primera asignatura.',
  addPeriodic: 'Añadir test',
  emptyPeriodic: 'Añade el primer test o examen periódico.',
  periodicHeading: 'Test y exámenes periódicos',
  colPeriod: 'Periodo',
  colExam: 'Test o examen',
  colWeight: 'Pond. NEI',
  expandCourse: 'Desplegar',
  collapseCourse: 'Contraer',
  enabledOn: 'Habilitado',
  enabledOff: 'Inactivo',
  stepCurrent: 'Paso actual',
  stepNext: 'Siguiente',
  emptyPath: 'El curso aún no tiene etapas. Añade la primera fase del itinerario.',
  matrixSelect: 'Subfase de la matriz',
  matrixHeading: 'Matriz de calificación',
  emptyModule: 'Añade la primera fase de este módulo.',
  coursesMeta: 'cursos',
  courseMeta: 'curso',
} as const;

export const PROGRAM_STUDIO_ROUTES = {
  list: '/catalogo/programas',
  standards: (id: string) => `/catalogo/programas/${id}/estandares`,
  flow: (id: string) => `/catalogo/programas/${id}/flujo`,
} as const;

export const CURRICULUM_DONUT = {
  circumference: 97.4,
} as const;
