export const TRAINING_ASSIGNMENT_FORM_COPY = {
  listBack: 'Volver al listado',
  lead: 'Matricula una promoción o un alumno a un programa.',
  individualLead: 'Vincula un alumno sin promoción a un programa.',
  groupCreateTitle: 'Matricular promoción',
  groupEditTitle: 'Editar matrícula de promoción',
  individualCreateTitle: 'Matricular alumno',
  individualEditTitle: 'Editar matrícula de alumno',
  loadingTitle: 'Cargando matrícula',
  loadingSubtitle: 'Un momento.',
  savingSubtitle: 'Guardando la matrícula y volviendo al listado.',
  savingLabel: 'Guardando matrícula',
  loadingLabel: 'Cargando matrícula',
  timelineKicker: 'Matrícula de promoción',
  timelineTitle: 'Progreso de matrícula',
  timelineLabel: 'Progreso de la matrícula',
  previous: 'Anterior',
  next: 'Siguiente',
  statusLabel: 'Estado de matrícula',
  caseLabel: 'Tipo de asignación',
  casePdi: 'PDI',
  casePde: 'PDE',
  caseCommission: 'Comisión',
  programLabel: 'Programa',
  promotionLabel: 'Promoción',
  participantsHeading: 'Participantes',
  participantsLead: 'Personas inscritas en la promoción. Quedan incluidas en esta matrícula.',
  participantsCountSuffix: 'inscritos',
  noParticipants: 'Esta promoción no tiene alumnos inscritos.',
  leadHeading: 'Jefe de instrucción',
  leadLead: 'Selecciona un responsable entre los perfiles disponibles.',
  leadSearch: 'Buscar jefe de instrucción',
  leadSearchPlaceholder: 'Nombre o indicativo',
  leadFallback: 'Jefe de instrucción',
  leadRequired: 'Selecciona un responsable.',
  dateLabel: 'Fecha programada',
  previewKicker: 'Resumen de matrícula',
  previewTitle: 'Todo listo para matricular',
  previewLead: 'Revisa el resumen antes de confirmar.',
  previewProgram: 'Programa',
  previewPromotion: 'Promoción',
  previewLeadPerson: 'Jefe de instrucción',
  previewDate: 'Fecha programada',
  previewPeople: 'Alumnos incluidos',
  previewPeopleSuffix: 'personas',
  previewNote: 'La matrícula quedará disponible para seguimiento después de confirmar.',
  unselected: 'Sin seleccionar',
  required: 'Este campo es obligatorio.',
  externalPerson: 'Persona externa',
  externalPlaceholder: 'Nombre de la persona externa',
  studentLabel: 'Alumno',
  emptyStudents: 'No hay alumnos sin promoción para matricular.',
  missionLabel: 'Misión individual',
  instructorLabel: 'Instructor',
  dateField: 'Fecha',
  saving: 'Guardando...',
  submit: 'Matricular',
  loadError: 'No hemos podido cargar los datos de matrícula.',
  toastTitle: 'Matrícula guardada',
  toastBody: 'La matrícula ya está registrada.',
  toastError: 'No se pudo guardar',
  persistError: 'No hemos podido guardar la matrícula.',
} as const;

export const TRAINING_ASSIGNMENT_GROUP_STEPS = [
  { label: 'Programa' },
  { label: 'Promoción' },
  { label: 'Jefe de instrucción' },
  { label: 'Fecha' },
  { label: 'Vista previa' },
] as const;
