export const TRAINING_PROGRAMMING_COPY = {
  createGroup: 'Matricular promoción',
  createIndividual: 'Matricular alumno',
  groupTab: 'Promoción',
  individualTab: 'Alumno',
  searchLabel: 'Buscar',
  searchPlaceholder: 'Promoción, alumno o programa',
  programLabel: 'Programa',
  programAll: 'Todos los programas',
  promotionLabel: 'Promoción',
  promotionAll: 'Todas las promociones',
  participants: 'Participantes',
  noParticipants: 'Sin participantes en la promoción',
  viewParticipants: 'Ver participantes',
  participantsModalTitle: 'Personas inscritas',
  colName: 'Nombre',
  colDocument: 'Documento',
  colIndicative: 'Indicativo',
  colEmail: 'Correo',
  emptyParticipants: 'No hay personas inscritas.',
  viewDetail: 'Ver detalle',
  emptyGroup: 'No hay matrículas de promoción con estos filtros.',
  emptyIndividual: 'No hay matrículas individuales con estos filtros.',
  cancelTitle: 'Cancelar matrícula',
  cancelMessage: 'La asignación pasará a Cancelado y no se podrá ejecutar.',
  cancelConfirm: 'Cancelar',
  cancelAria: 'Cancelar matrícula',
} as const;
