import { MISSION_EXECUTION_BOARD_PATH, NAV_ROUTES } from '@layout/navigation/data/nav-routes.constants';

export const MISSION_EXECUTION_ROUTES = {
  inbox: NAV_ROUTES.missionExecution,
  board: MISSION_EXECUTION_BOARD_PATH,
  workspace: (executionId: string) => `${NAV_ROUTES.missionExecution}/${executionId}`,
} as const;

export const MISSION_EXECUTION_COPY = {
  kicker: 'Centro de operaciones diario',
  datePrefix: 'Operaciones del día',
  searchLabel: 'Buscar',
  searchPlaceholder: 'Alumno, misión o programa',
  dateLabel: 'Fecha',
  filterLabel: 'Estado del día',
  filter: {
    all: 'Todas',
    scheduled: 'Programadas',
    'in-progress': 'En curso',
    completed: 'Finalizadas',
    cancelled: 'Canceladas',
  },
  kpi: {
    scheduled: 'Programadas',
    inProgress: 'En curso',
    completed: 'Finalizadas',
    cancelled: 'Canceladas',
  },
  listTitle: 'Misiones del día',
  listCount: 'registros',
  nextTitle: 'Próximas ejecuciones',
  fidsExpand: 'Ampliar',
  fidsCollapse: 'Cerrar',
  fidsReload: 'Recargar',
  nextNow: 'Siguiente',
  nextTime: 'Hora',
  nextCrew: 'AP / IP',
  nextAircraft: 'Aeronave',
  nextBoarding: 'Embarque',
  nextState: 'Estado',
  fidsBoarding: 'Embarque',
  fidsClosing: 'Cierre',
  roleIp: 'IP',
  roleAp: 'AP',
  empty: 'No hay misiones que coincidan con la búsqueda o el filtro.',
  detail: 'Ver detalle',
  grade: 'Calificar',
  flightOrder: 'Orden de vuelo',
  orderTitle: 'Orden de vuelo operacional',
  orderLead: 'Permiso para ejecutar la misión. Los datos no se editan en esta vista.',
  orderClose: 'Cerrar',
  pagerPerPage: 'Por página:',
  pagerPerPageLabel: 'Filas por página',
  orderMission: 'Misión académica',
  orderCrew: 'Tripulación asignada',
  orderAircraftBlock: 'Aeronave',
  orderSlotBlock: 'Horario y slot de vuelo',
  orderNotesBlock: 'Observaciones / notas operativas',
  orderStudentRole: 'Alumno',
  orderInstructorRole: 'Instructor',
  orderCallsign: 'Indicativo',
  orderSlotLabel: 'Slot programado',
  orderDurationLabel: 'Duración estimada',
  orderFields: {
    number: 'Número de orden de vuelo',
    date: 'Fecha',
    status: 'Estado',
    aircraft: 'Matrícula de la aeronave',
    student: 'Alumno / piloto',
    instructor: 'Instructor de vuelo',
    authorizer: 'Responsable que autoriza',
    departure: 'Hora prevista de salida',
    arrival: 'Hora prevista de llegada',
    duration: 'Tiempo estimado',
    notes: 'Información adicional de la orden',
  },
  fields: {
    mission: 'Misión',
    student: 'Alumno',
    program: 'Programa',
    phase: 'Fase',
    subphase: 'Subfase',
    instructor: 'Instructor',
    aircraft: 'Aeronave',
    time: 'Hora',
    progress: 'Avance',
  },
  status: {
    scheduled: 'Programada',
    'in-progress': 'En curso',
    completed: 'Finalizada',
    cancelled: 'Cancelada',
  },
  orderStatus: {
    draft: 'Borrador',
    scheduled: 'Programada',
    'in-progress': 'En curso',
    completed: 'Completada',
    cancelled: 'Cancelada',
  },
} as const;
