export const PROGRAMMING_ROUTES = {
  board: '/catalogo/matricula',
  assignments: '/catalogo/matricula/asignacion',
  record: (userId: string) => `/catalogo/avance-academico/${userId}`,
  missions: '/catalogo/programacion-entrenamiento',
} as const;

export const PROGRAMMING_COPY = {
  title: 'Matrícula',
  lead: 'Matricula al programa, no a cada misión. Tierra, simulador y aire forman parte del mismo plan. Las misiones se asignan desde esta misma pantalla.',
  needsSquadron:
    'Selecciona un escuadrón en el encabezado para matricular. Esta pantalla reutiliza el contexto de unidad y escuadrón.',
  loadError: 'No hemos podido cargar la matrícula. Recarga la página.',
  loadingTitle: 'Cargando matrícula',
  loadingSubtitle: 'Programas de alta y alumnos vinculados.',
  loadingLabel: 'Cargando matrícula',
  tabPrograms: 'Programas',
  tabRoster: 'Alumnos matriculados',
  tabResults: 'Resultados',
  tabAssignments: 'Asignación de misiones',
  emptyPrograms: 'No hay programas en el catálogo.',
  emptyRoster: 'Nadie está matriculado todavía en el programa seleccionado.',
  emptyCandidates: 'No hay alumnos disponibles en esa promoción.',
  culminatedBadge: 'Culminado',
  culminatedHint: 'La calificación ya finalizó. Este programa es de consulta.',
  yearPrefix: 'Año',
  enrollPromotion: 'Matricular promoción',
  enrollStudent: 'Matricular alumno',
  enrolledMeta: 'matriculados activos',
  enrolledMetaOne: 'matriculado activo',
  rosterHeading: 'Efectivos matriculados',
  searchLabel: 'Buscar',
  searchPlaceholder: 'Alumno o indicativo',
  colStudent: 'Alumno',
  colIndicative: 'Indicativo',
  colSource: 'Origen',
  colPromotion: 'Promoción',
  colEnrollment: 'Matrícula',
  colDate: 'Fecha',
  colRank: 'Puesto',
  colResult: 'Resultado académico',
  colAverage: 'Promedio',
  colSpecialty: 'Especialidad',
  outcomePassed: 'Aprobado',
  outcomeFailed: 'Desaprobado',
  outcomeOpen: 'En curso',
  viewRecord: 'Abrir legajo',
  dropStudent: 'Dar de baja',
  enrollModeLabel: 'Tipo de matrícula',
  enrollModePromotion: 'Promoción',
  enrollModeIndividual: 'Individual',
  enrollTitlePromotion: 'Matricular una promoción',
  enrollTitleStudent: 'Matricular un alumno',
  enrollProgram: 'Programa',
  enrollPromotionField: 'Promoción',
  enrollStudentField: 'Alumno',
  enrollAvailable: 'Alumnos disponibles',
  enrollSelected: 'seleccionados',
  enrollDate: 'Fecha de matrícula',
  enrollConfirmPromotion: 'Matricular promoción',
  enrollConfirmStudent: 'Matricular',
  enrollNeedStudents: 'Selecciona al menos un alumno de la promoción.',
  enrollNeedStudent: 'Selecciona el alumno a matricular.',
  enrollCancel: 'Cancelar',
  noPromotion: 'Sin promoción',
  dropTitle: 'Dar de baja alumno',
  dropLead: 'El historial se conserva. No se podrán asignar misiones ni evaluaciones nuevas.',
  dropReason: 'Motivo',
  dropDate: 'Fecha',
  dropConfirm: 'Confirmar baja',
  toastPromotion: 'Promoción matriculada',
  toastStudent: 'Alumno matriculado',
  toastBody: 'Quedan vinculados al programa. Las misiones se asignan después, cuando corresponda.',
  toastDropped: 'Alumno dado de baja',
  toastDroppedBody: 'El historial se mantiene. No hay nuevas actividades académicas.',
  none: '—',
  pickProgram: 'Selecciona un programa para ver matrícula y resultados.',
  enrollmentStatus: {
    active: 'Activo',
    suspended: 'Suspendido',
    withdrawn: 'Retirado',
    dropped: 'Dado de baja',
    completed: 'Completado',
  },
  closeReasons: [
    { value: 'Incumplimiento académico', label: 'Incumplimiento académico' },
    { value: 'Retiro voluntario', label: 'Retiro voluntario' },
    { value: 'Motivo médico', label: 'Motivo médico' },
    { value: 'Suspensión temporal de instrucción', label: 'Suspensión temporal de instrucción' },
  ],
} as const;
