export const FLIGHT_ORDER_ROUTES = {
  board: '/catalogo/orden-de-vuelo',
  dispatch: '/catalogo/despacho-diario',
} as const;

export const FLIGHT_ORDER_DEFAULT_TIME = '08:30';
export const FLIGHT_ORDER_DATE_MAX_YEAR = 2035;

export const FLIGHT_ORDER_COPY = {
  kicker: 'Plan operacional diario',
  title: 'Generación de orden de vuelo y asignación',
  lead: 'Planifica la siguiente misión de cada alumno: el avance es individual, aunque compartan promoción y programa.',
  modeLabel: 'Listado de alumnos',
  rosterCount: 'alumnos',
  treeTitle: 'Árbol académico',
  treeModuleLabel: 'Módulo del programa',
  treeModule: {
    ground: 'Tierra',
    air: 'Aire',
    simulator: 'Simulador',
  },
  treeModuleEmpty: 'Este módulo no tiene fases en el programa seleccionado.',
  emptyEvaluations: 'Este curso no tiene evaluaciones para mostrar.',
  emptyMissions: 'Esta subfase no tiene misiones para mostrar.',
  treeMissions: 'Misiones',
  groundNa: 'NA',
  groundPe: 'PE',
  groundPt: 'PT',
  groundCoef: 'coef.',
  groundGrade: 'Nota',
  groundPending: 'Pendiente',
  evaluationsWord: 'evaluaciones',
  groundAssignPending: 'Pendiente',
  toastGroundAssigned: 'Curso de tierra actualizado',
  toastGroundAssignedBody: 'El expediente del alumno ya refleja los cursos habilitados.',
  railTitle: 'Trayectoria del programa',
  kpiCompleted: 'Misiones completadas',
  kpiCoursesCompleted: 'Cursos completados',
  kpiHours: 'Horas registradas',
  kpiAverage: 'Promedio',
  kpiStatus: 'Estado del programa',
  academicStatus: {
    'in-progress': 'En formación',
    completed: 'Programa completado',
    suspended: 'Suspendido',
  },
  sheetKicker: 'Ficha de asignación',
  missionIndex: 'Posición',
  phaseSubphase: 'Fase / subfase',
  noHistory: 'Sin ejecuciones previas. Primera asignación de esta misión.',
  observationsLabel: 'Observaciones para el despacho',
  observationsHint: 'Opcional. Quedan en la ejecución programada.',
  scheduleMission: 'Programar',
  enableMission: 'Habilitar',
  viewOrder: 'Ver orden',
  blockedMission: 'Esta misión todavía no puede programarse.',
  missionStatus: {
    completed: 'Completada',
    scheduled: 'Programada',
    available: 'Disponible',
    blocked: 'Bloqueada',
    recovery: 'Recuperación',
    update: 'Actualización',
  },
  legendLabel: 'Estados',
  hoursPlan: 'horas planificadas',
  dualWith: 'Instructor',
  emptyTrainee: 'Selecciona un alumno para ver su avance y programar la siguiente misión.',
  emitTitle: 'Emitir orden de vuelo',
  viewTitle: 'Orden de vuelo',
  readonlyNotice: 'Consulta de la orden registrada. Los datos no se pueden modificar.',
  needsSquadron: 'Selecciona un escuadrón en el encabezado. Esta pantalla reutiliza el contexto operativo.',
  loadError: 'No hemos podido cargar el tablero de órdenes de vuelo. Recarga la página.',
  loadingTitle: 'Cargando órdenes de vuelo',
  loadingSubtitle: 'Alumnos matriculados y recursos del contexto.',
  loadingLabel: 'Cargando órdenes de vuelo',
  rosterPromo: 'Promoción',
  rosterIndividual: 'Alumno',
  rosterLabel: 'Alumnos',
  searchLabel: 'Buscar persona',
  searchPlaceholder: 'Nombre, indicativo, programa o promoción',
  promotionLabel: 'Promoción',
  programLabel: 'Programa',
  tableHeading: 'Alumnos del contexto',
  tableCaption: 'Alumnos matriculados listos para emitir o actualizar una orden de vuelo',
  colStudent: 'Alumno',
  colIndicative: 'Indicativo',
  colProgram: 'Programa',
  colPromotion: 'Promoción',
  colNext: 'Siguiente misión',
  colProgress: 'Avance',
  colStatus: 'Estado',
  emptySearch: 'No hay alumnos que coincidan con la búsqueda o los filtros.',
  goDispatch: 'Ir al despacho diario',
  cohortKicker: 'Promoción',
  enrolledCount: 'alumnos matriculados',
  averageProgress: 'Progreso promedio',
  programsLabel: 'Programas',
  individualsTitle: 'Alumnos matriculados de forma directa',
  individualsLead: 'Alumnos fuera de una promoción ordinaria: reentrenamiento, nivelación o pase de unidad.',
  registered: 'registrados',
  assign: 'Asignar orden',
  progressLabel: 'Avance curricular',
  ofMissions: 'de',
  missionsWord: 'misiones',
  coursesWord: 'cursos',
  subjectsWord: 'asignaturas',
  completed: 'completado',
  nextMission: 'Siguiente misión',
  hoursSuffix: 'h',
  emptyPromo: 'No hay alumnos de promoción para este filtro.',
  emptyIndividual: 'No hay alumnos directos para este filtro.',
  emptyCohort: 'No hay promociones con matrícula activa en este contexto.',
  documentKicker: 'Documento de operaciones',
  draft: 'Borrador activo',
  correlative: 'Correlativo',
  operationDate: 'Fecha de operación',
  traineeKicker: 'Alumno asignado',
  traineeEmpty: 'Selecciona un alumno del listado',
  missionLabel: 'Misión curricular asignada',
  recommended: 'Recomendado por el plan',
  dateLabel: 'Fecha prevista',
  timeLabel: 'Hora prevista',
  timeHint: 'Formato 24 h, por ejemplo 08:30',
  durationLabel: 'Duración estimada',
  aircraftLabel: 'Aeronave asignada',
  available: 'disponibles',
  instructorLabel: 'Instructor de vuelo',
  shiftLabel: 'Turno',
  shift: {
    morning: 'Mañana',
    afternoon: 'Tarde',
    night: 'Noche',
  },
  notice:
    'Al emitir la orden, el slot queda programado en el despacho diario con instructor, aeronave, fecha y hora.',
  emit: 'Emitir orden',
  update: 'Actualizar orden',
  scheduledNotice:
    'Este alumno ya tiene una orden emitida para la siguiente misión. Al guardar se actualiza instructor, aeronave, fecha y hora del slot.',
  lastCompleted: 'Última misión cerrada',
  preview: 'Vista previa',
  previewTitle: 'Vista previa de la orden',
  previewClose: 'Cerrar',
  cannotIssue: 'Tu rol no puede emitir órdenes de vuelo.',
  cannotComplete: 'Este alumno ya completó las misiones del programa.',
  cannotModifyCulminated:
    'El programa está culminado. Puedes consultar el curso y la trazabilidad de las órdenes de vuelo, sin modificarlas.',
  toastIssued: 'Orden de vuelo emitida',
  toastIssuedBody: 'El slot ya está disponible en el despacho diario.',
  previewStudent: 'Alumno',
  previewMission: 'Misión',
  previewInstructor: 'Instructor',
  previewAircraft: 'Aeronave',
  previewWhen: 'Fecha y hora',
  none: '—',
  months: [
    'enero',
    'febrero',
    'marzo',
    'abril',
    'mayo',
    'junio',
    'julio',
    'agosto',
    'septiembre',
    'octubre',
    'noviembre',
    'diciembre',
  ],
} as const;
