export const DISPATCH_ROUTES = {
  board: '/catalogo/despacho-diario',
  training: '/catalogo/programacion-entrenamiento',
  trainingEdit: (id: string) => `/catalogo/programacion-entrenamiento/individual/${id}/editar`,
  workspace: (executionId: string) => `/catalogo/ejecucion-misiones/${executionId}`,
  record: (userId: string) => `/catalogo/avance-academico/${userId}`,
} as const;

export const DISPATCH_COPY = {
  title: 'Programación y despacho diario',
  kicker: 'Despacho diario',
  lead:
    'Supervise los vuelos programados del día, despache a cabina para habilitar la rúbrica del instructor y gestione incidencias de rampa antes del despegue.',
  needsSquadron: 'Selecciona un escuadrón en el encabezado. Esta pantalla reutiliza el contexto operativo.',
  loadError: 'No hemos podido cargar el tablero de despacho. Recarga la página.',
  protocolTitle: 'Despacho a cabina',
  protocolLead:
    'Al iniciar la misión, la rúbrica queda disponible en el workspace del instructor. El cronómetro de bloque se registra al pasar la ejecución a en curso.',
  datePrev: 'Día anterior',
  dateNext: 'Día siguiente',
  todayPrefix: 'Hoy',
  instructorFilter: 'Instructor',
  instructorAll: 'Todos los instructores',
  metricTotal: 'Flujo del día',
  metricTotalHint: 'Misiones programadas',
  metricCapacity: 'Capacidad de slots',
  metricAssigned: 'asignado',
  metricAirborne: 'En vuelo',
  metricAirborneHint: 'Ejecuciones en curso',
  metricClosed: 'Cierre docente',
  metricClosedHint: 'Calificadas y cerradas',
  metricReady: 'Listas para iniciar',
  metricReadyHint: 'Siguiente slot a despachar',
  boardTitle: 'Slots de vuelo',
  tabAll: 'Todas',
  tabAirborne: 'En vuelo',
  tabPending: 'Pendientes',
  tabClosed: 'Concluidas',
  colSlot: 'Hora',
  colMission: 'Misión',
  durationPrefix: 'DUR',
  colStudent: 'Alumno',
  colInstructor: 'Instructor',
  colAircraft: 'Aeronave',
  colStatus: 'Estado',
  colAction: 'Acción',
  kindReady: 'Programada / lista',
  kindAirborne: 'En ejecución',
  kindPending: 'Programada',
  kindClosed: 'Calificada',
  kindCancelled: 'Cancelada',
  actionDispatch: 'Iniciar misión y despachar a cabina',
  actionLive: 'Abrir hoja de calificación',
  actionRecord: 'Ver legajo',
  actionPrereq: 'Verificar requisitos',
  actionNone: 'Sin acción',
  empty: 'No hay slots para esta fecha y filtros.',
  showing: 'Mostrando',
  of: 'de',
  slotsWord: 'slots',
  exportManifest: 'Manifiesto diario',
  exportSiga: 'Exportar listado',
  exportSoon: 'La exportación no está disponible en esta versión.',
  preflightKicker: 'Verificación previa al despacho',
  preflightTitle: 'Requisitos del slot seleccionado',
  preflightReady: 'Listo para salida',
  preflightBlocked: 'Faltan requisitos',
  preflightOpenRubric: 'Abrir rúbrica en el workspace',
  rampKicker: 'Gestión de rampa',
  rampTitle: 'Incidencias y contingencia',
  rampLead:
    'Si la aeronave o el instructor no están disponibles, reprograma el slot o cámbialo antes de despachar. La cancelación deja el slot fuera de ejecución.',
  reschedule: 'Reprogramar slot',
  swap: 'Cambiar aeronave o instructor',
  cancel: 'Cancelar slot',
  cancelTitle: 'Cancelar slot',
  cancelMessage: 'El slot pasará a cancelado y no se podrá despachar. La programación operativa conserva el registro.',
  cancelConfirm: 'Cancelar slot',
  toastDispatched: 'Misión despachada a cabina',
  toastDispatchedBody: 'La rúbrica ya está habilitada en el workspace del instructor.',
  toastCancelled: 'Slot cancelado',
  toastCancelledBody: 'El estado ya está actualizado.',
  noExecution: 'Este slot aún no tiene ejecución. Ábrelo en la programación de misiones.',
  none: '—',
  months: ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'],
} as const;
