export const DASHBOARD_COPY = {
  image: '/dashboard-hero.jpg',
  imageAlt:
    'Cabina de instrucción al anochecer: alumno e instructor en un entrenador, con indicadores tácticos y formación de aeronaves.',
  error: 'No hemos podido cargar el panel. Recarga o vuelve en unos minutos.',
  needsSquadron:
    'Selecciona un escuadrón en el encabezado para acotar el panel. No se vuelve a pedir unidad ni escuadrón en esta pantalla.',
  missingContext: 'Confirma tu contexto operativo para ver el panel.',
  director: {
    eyebrow: 'Dirección académica',
    title: 'Supervisión de la operación',
    subtitle: 'Indicadores del contexto de unidad y escuadrón seleccionado en el encabezado.',
    kpis: {
      students: 'Alumnos activos',
      programs: 'Programas activos',
      today: 'Misiones del día',
      hours: 'Horas voladas',
      promotions: 'Promociones activas',
    },
    programs: 'Estado de programas',
    missions: 'Actividad de misiones',
    distribution: 'Distribución de alumnos',
    trend: 'Tendencia de horas de vuelo',
    activity: 'Resumen de actividad académica',
    alerts: 'Alertas',
    scheduled: 'Programadas',
    inProgress: 'En curso',
    completed: 'Completadas',
  },
  instructor: {
    eyebrow: 'Instrucción',
    title: 'Actividades pendientes',
    subtitle: 'Misiones, alumnos y evaluaciones a tu cargo en el contexto operativo actual.',
    assignedMissions: 'Misiones asignadas',
    assignedStudents: 'Alumnos asignados',
    pendingEvaluations: 'Evaluaciones pendientes',
    upcoming: 'Próximas misiones',
    pendingStudents: 'Alumnos con actividades pendientes',
    toGrade: 'Evaluaciones por completar',
    recent: 'Últimas calificaciones',
    progress: 'Avance de los alumnos asignados',
  },
  student: {
    eyebrow: 'Mi formación',
    title: 'Seguimiento académico',
    subtitle: 'Tu avance, horas, promedio y próximas actividades de instrucción.',
    progress: 'Avance académico',
    hours: 'Horas acumuladas',
    average: 'Promedio',
    next: 'Próxima misión',
    program: 'Programa actual',
    phase: 'Fase actual',
    subphase: 'Subfase actual',
    evaluations: 'Últimas evaluaciones',
    history: 'Historial reciente de misiones',
    pending: 'Actividades pendientes',
  },
  empty: 'Sin datos en este contexto.',
  none: '—',
} as const;
